model_config:
    load_model: True
    model_path: "storage/epsilon_decay_1000_2.ckpt"
    n_actions: 9
    n_hidden: 1
    size_hidden: 256
    use_cuda: True

training_config:
    render: False
    n_episodes: 5000
    learning_rate: 0.0001
    batch_size: 64
    gamma: 0.99
    n_update_target: 6 # how many episode to update the target network
    memory_size: 100000
    max_episode_step: 500
    random_seed: 1234
    save_model_path: "storage/epsilon_decay_1000_2.ckpt"
    use_fix_epsilon: True
    fix_epsilon: 0.1
    epsilon_start: 0.4
    epsilon_final: 0.1
    epsilon_decay: 500
    exp_number: 2  # experiment number
    save_best: False


