model_config:
    load_model: False # If set true, you must specify the model path, otherwise train a new model
    model_path: "storage/exp_1.ckpt" # the path to load the model
    n_states: 6
    n_actions: 1
    n_hidden: 1 # hidden layer number
    size_hidden: 256 # hidden layer size
    use_cuda: True

training_config:
    n_epochs: 50 # how many epoches to train
    learning_rate: 0.001 
    batch_size: 70
    save_model_flag: True
    save_model_path: "storage/exp_1.ckpt" # the path to save the model
    save_loss_fig: True
    save_loss_fig_frequency: 30 # how many every epochs to save the loss figure 
    exp_number: 1  # experiment number

dataset_config:
    n_max_steps: 1000
    n_random_episodes: 5
    testset_split: 0.2 # testset's portion in the random dataset, the rest portion is the training set
    n_mpc_episodes: 5

mpc_config:
    horizon: 15
    numb_bees: 8
    max_itrs: 8 # testset's portion in the random dataset, the rest portion is the training set
    gamma: 0.9
    action_low: -5
    action_high: 5
