model_config:
    load_model: False # If set true, you must specify the model path, otherwise train a new model
    model_path: "storage/exp_4.ckpt" # the path to load the model
    n_actions: 9
    n_hidden: 2 # hidden layer number
    size_hidden: 128 # hidden layer size
    use_cuda: False

training_config:
    render: True # render the environment, set false to accelerate training. test.py does not need this parameter
    n_episodes: 20000 # how many episodes to train
    learning_rate: 0.0001
    batch_size: 32
    gamma: 0.98
    n_update_target: 4 # how many episode to update the target network
    memory_size: 100000 # replay memory buffer size
    max_episode_step: 2000 # maximum steps per episode
    random_seed: 1234 # do not have to change this parameter
    save_model_path: "storage/test.ckpt" # the path to save the model
    use_fix_epsilon: True # set true to use a fixed epsilon, otherwise the episilon will decay
    fix_epsilon: 0.1
    epsilon_start: 0.5 # episilon decay start
    epsilon_final: 0.2 # episilon decay end
    epsilon_decay: 200 # bandwidth
    exp_number: 7  # experiment number
    save_best: False

