model_config:
    load_model: False
    model_path: "storage/epsilon_decay_4000.ckpt"
    n_actions: 9
    n_hidden: 2
    size_hidden: 128
    use_cuda: True

training_config:
    render: False
    n_episodes: 15000
    learning_rate: 0.0003
    batch_size: 64
    gamma: 0.995
    n_update_target: 4 # how many episode to update the target network
    memory_size: 1000000
    max_episode_step: 4000
    random_seed: 1234
    save_model_path: "storage/epsilon_decay_4000.ckpt"
    use_fix_epsilon: False
    fix_epsilon: 0.3
    epsilon_start: 0.9
    epsilon_final: 0.05
    epsilon_decay: 4000
    exp_number: 0  # experiment number


